### ISSUE TITLE
Issue with body parameters

### ISSUE THREAD

**Issue by ced42** [schemathesis/schemathesis#1150]
Hello,

# Describe the bug

It looks like body parameters are not taken into account.
I have tried with my own code and the example given in schemathesis.

When I type the following command in example folder of schemathesis (SCHEMA_URL and PYTHONPATH are set):
`schemathesis run $SCHEMA_URL`

I have these errors:
```
===================================================================== Schemathesis test session starts =====================================================================
platform Linux -- Python 3.9.2, schemathesis-3.6.4, hypothesis-6.10.1, hypothesis_jsonschema-0.19.1, jsonschema-3.2.0
rootdir: /home/clachat/wd/codes/python/schemathesis/example
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/clachat/wd/codes/python/schemathesis/example/.hypothesis/examples')
Schema location: http://10.19.65.43:5000/api/openapi.json
Base URL: http://10.19.65.43:5000/api
Specification version: Open API 3.0.0
Workers: 1
Collected API operations: 3

GET /api/bookings/{booking_id} F                                                                                                                                      [ 33%]
POST /api/bookings/ F                                                                                                                                                 [ 66%]
GET /api/bookings/ .                                                                                                                                                  [100%]

================================================================================= FAILURES =================================================================================
____________________________________________________________________ GET /api/bookings/{booking_id} [P] ____________________________________________________________________
1. Received a response with 5xx status code: 500

Path parameters : {'booking_id': 2147483648}
Headers         : {'User-Agent': 'schemathesis/3.6.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

----------

Response payload: `{"type": "about:blank", "title": "Internal Server Error", "detail": "Server got itself in trouble", "status": 500}`

Run this Python code to reproduce this failure: 

    requests.get('http://10.19.65.43:5000/api/bookings/2147483648', headers={'User-Agent': 'schemathesis/3.6.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'})

Or add this option to your command line parameters: --hypothesis-seed=270120329738940535782402410985261502850
_________________________________________________________________________ POST /api/bookings/ [P] __________________________________________________________________________
1. Received a response with 5xx status code: 500

Headers         : {'User-Agent': 'schemathesis/3.6.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Content-Length': '2'}
Body            : {}

----------

Response payload: `{"type": "about:blank", "title": "Internal Server Error", "detail": "Server got itself in trouble", "status": 500}`

Run this Python code to reproduce this failure: 

    requests.post('http://10.19.65.43:5000/api/bookings/', headers={'User-Agent': 'schemathesis/3.6.4', 'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2'})

Or add this option to your command line parameters: --hypothesis-seed=295339955890644101447220614181709515798
================================================================================= SUMMARY ==================================================================================

Performed checks:
    not_a_server_error                    120 / 135 passed          FAILED 

======================================================================= 1 passed, 2 failed in 1.24s ========================================================================
```

From docker-compose, one of the errors is:
```
web_1  | ERROR:connexion.apis.aiohttp_api:Error handling request
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.8/site-packages/connexion/apis/aiohttp_api.py", line 56, in problems_middleware
web_1  |     response = yield from handler(request)
web_1  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 110, in impl
web_1  |     return await handler(request)
web_1  |   File "/usr/local/lib/python3.8/site-packages/connexion/decorators/coroutine_wrappers.py", line 23, in wrapper
web_1  |     connexion_response = yield from connexion_response
web_1  |   File "/example/app/views.py", line 23, in create_booking
web_1  |     booking_id=body["id"],
web_1  | KeyError: 'id'
web_1  | INFO:connexion.aiohttp_app:172.25.0.1 [05/May/2021:12:43:51 +0000] "POST /api/bookings/ HTTP/1.1" 500 284 "-" "schemathesis/3.6.4"
```

*id* is not found in the body, so it looks like *id* is not given.

# To reproduce the issue

Try the beginning of the examples in the schemathesis/example folder:
```
docker-compose up
export SCHEMA_URL="http://0.0.0.0:5000/api/openapi.json"
export PYTHONPATH=$(pwd)
schemathesis run $SCHEMA_URL
```

# Environment

- Python 3.9.2
- schemathesis 3.6.3 and 3.6.4

Regards,
Cédric

**Comment by Stranger6667** [comment]
Hi Cédric,

This behavior is expected. It illustrates a bug - the `Booking` schema does not define the `id` field as required

**Comment by ced42** [comment]
Hi Dmitry,

Thank you for your answer.
Sorry, I didn't understand that.

So, I will explain the case with my own code:
The API schema (as Open API JSON format) produced by flasgger is (some parts have been cleaned):
```
{
  "basePath": "/adduser_python_admin",
  "definitions": {
    "UserSchema": {
      "properties": {
        "email": {
          "format": "email",
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "shortName": {
          "type": "string"
        }
      },
      "required": [
        "shortName"
      ],
      "type": "object"
    },
    "user.Credentials": {
      "properties": {
        "otpSecret": {
          "description": "OTP",
          "type": "string"
        },
        "password": {
          "description": "password",
          "type": "string"
        }
      }
    },
    "user.Id": {
      "properties": {
        "userId": {
          "description": "Id of created user",
          "type": "integer"
        }
      }
    },
    "user.State": {
      "properties": {
        "state": {
          "description": "wanted state",
          "type": "string"
        }
      }
    }
  },
  "info": {
  },
  "paths": {
   "/v1/pcc/{pcc_uid}/user": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "deprecated": false,
        "description": "Create an user for a PCC",
        "operationId": "admin.createUser",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": false,
            "schema": {
              "$ref": "#/definitions/UserSchema"
            }
          },
          {
            "in": "path",
            "name": "pcc_uid",
            "required": true,
            "type": "string"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "201": {
            "description": "Success request",
            "schema": {
              "$ref": "#/definitions/user.Id"
            }
          },
          "400": {
            "description": "Validation error"
          }
        },
        "schemes": [],
        "security": [],
        "summary": "Create the user ",
        "tags": [
          "admin"
        ]
      }
    }
  },
  "swagger": "2.0"
}
```

When I run a test on the route "/v1/pcc/{pcc_uid}/user" I have these errors:
```
E           schemathesis.exceptions.CheckFailed: 
E           
E           1. Received a response with 'text/html; charset=utf-8' Content-Type, but it is not declared in the schema.
E           
E           Defined content types: application/json
E           
E           ----------
E           
E           Response payload: `No data to validate`
E           
E           Run this Python code to reproduce this response: 
E           
E               requests.post('http://10.19.65.43:20810/adduser_python_admin/v1/pcc/lim1c-1/user', headers={'User-Agent': 'schemathesis/3.6.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '0'})
```

In my opinion, the body parameters (as email, firstName, lastName, shortName) are not given.
Maybe, my schema is wrong.

**Comment by Stranger6667** [comment]
Thank you for supplying a schema :)

The problem comes from `required: false` in the body parameter definition:

```json
{
    "in": "body",
    "name": "body",
    "required": false,
    "schema": {
        "$ref": "#/definitions/UserSchema"
    }
}
```

As it is not required, then one of the options Schemathesis tries is not sending any payload at all. I hope that it clarifies the situation :) Let me know if you have any further questions

**Comment by ced42** [comment]
Hello Dmitry,

Thank you very much!
I think that my issue comes from Flasgger.

Have a good day,
Cédric.

**Comment by Stranger6667** [comment]
You are very welcome, Cédric!

Feel free to reach out to me in case you have any further questions :)

Cheers,
Dmitry
