### ISSUE TITLE
[FEATURE] Combine explicit examples with generated tests

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#1158]
Now examples are tested separately, but it seems like it should be beneficial to use examples in tests that use only generated data (it is also concluded in section 5.3.3 at [this paper](https://patricegodefroid.github.io/public_psfiles/fse2020.pdf))

Let's say we have the following body schema:

```json
{
    "properties": {
        "foo": {"type": "string"}
    },
    "required": ["foo"]
}
```

And an example for the `foo` property - "bar", then the gist is to use `st.text() | st.just("bar")` for the `foo` property instead of just using `st.text()`. It similarly applies to other cases

The usual obstacle for Schemathesis is bumping into the validation layer because Schemathesis doesn't know much about valid values - using the approach above should improve this situation.

**Comment by mbiuki** [comment]
## 1)
I am not sure how I can use examples the way mentioned above in my pytest construct. I have the following:

```python
...

schema = schemathesis.from_path( openApiFilePath,
                                 skip_deprecated_operations=True,
                                 validate_schema=True,
                                 code_sample_style="curl",
                                 base_url=URL)


@pytest.fixture(scope="session")
def token_getter():
    # The best way to solve it is to call a TTL-cached version of 
    # the printToken function inside test_api.
    @cached(cache=TTLCache(maxsize=1,ttl=int(token_refresh_interval) - THRESHOLD))
    def retrieve_token():
        return printToken()

    return retrieve_token

schemathesis.register_string_format("uuid", st.uuids().map(str))

@schema.parametrize()
@schema.given(data=st.data())
def test_api(data, case, token_getter):
    token = token_getter()
    case.headers = case.headers or {}
    case.headers["Authorization"] = f"Bearer {token}"
    case.headers["X-KLM-ID"] = X_KLM_ID
    # the following are samples and must not be used, provide your own body fixed ids
    case.path_parameters["personId"] = "7dafa30d-25d9-4e1c-80b6-f842e8412f51"
    case.path_parameters["managedAgentId"] = "316e513d-bcf1-474f-8273-8c0e96f9bd4f"
    case.path_parameters["managedAgent"] = "316e513d-bcf1-474f-8273-8cf096f9bd4f"
    case.path_parameters["userId"] = "308051ea-8724-41ab-b22b-46dda920e9a6"
    case.path_parameters["groupId"] = "8537e5dc-0359-4af9-b88c-dcaf7b46976e"
    case.path_parameters["alertId"] = "b12b26e1-cb8c-4d72-8bdc-052aac79d981"
    case.path_parameters["ids"]  = data.draw(st.sampled_from(["b12b26e1-9b8c-4d72-8bdc-052aac79d981", "8dc3ade9-e2af-4c47-9309-350aab23517d"]))
    case.path_parameters["groupKey"] = "MSxFdmVudDo6RW5kcG9pbnQ6Ok5vdFByu3RlY3RlZCw1MTMs"
    case.path_parameters["parentGroupId"] = "8537e5dc-0359-4af9-b88c-dcaj7b46376e"
    case.call_and_validate()
```
For UUIDs, those are fixed body parameter values; can I run something like this:

```python
...
...

schemathesis.register_string_format("uuid", st.uuids().map(str))

@schema.parametrize()
@schema.given(data=st.data())
@schema.given(personId=st.just("7dafa30d-25d9-4e1c-80b6-f842e8412f51"))
@schema.given(managedAgentId=st.just("316e513d-bcf1-474f-8273-8c0e96f9bd4f"))
@schema.given(managedAgent=st.just("316e513d-bcf1-474f-8273-8cf096f9bd4f"))
...
def test_api(data, case, token_getter):
    token = token_getter()
    case.headers = case.headers or {}
    case.headers["Authorization"] = f"Bearer {token}"
    case.headers["X-KLM-ID"] = X_KLM_ID
    case.call_and_validate()
```
Not sure if this is correct?

## 2)
On a side note, it looks like I have problem with `st.data` --- I get the following error:
```bash
Falsifying explicit example: test_api(
    case=Case(headers={'Authorization': 'Bearer ', 'X-KLM-ID': '...'}, query={'lastSeenBefore': 'PT200S', 'lastSeenAfter': '-PT200S', 'cloud': 'i-3bc4829309,42349c92'}),
    token_getter=<function run_schemathesis.token_getter.<locals>.retrieve_token>,
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 345, in execute_explicit_examples
    state.execute_once(
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 619, in execute_once
    result = self.test_runner(data, run)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/executors.py", line 52, in default_new_style_executor
    return function(data)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 615, in run
    return test(*args, **kwargs)
TypeError: test_api() missing 1 required positional argument: 'data'

Falsifying explicit example: test_api(
    case=Case(headers={'Authorization': 'Bearer ', 'X-KLM-ID': '...'}, query={'lastSeenBefore': '-PT20M', 'lastSeenAfter': 'PT20M', 'cloud': 'i-3bc4829309,42349c92'}),
    token_getter=<function run_schemathesis.token_getter.<locals>.retrieve_token>,
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 345, in execute_explicit_examples
    state.execute_once(
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 619, in execute_once
    result = self.test_runner(data, run)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/executors.py", line 52, in default_new_style_executor
    return function(data)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 615, in run
    return test(*args, **kwargs)
TypeError: test_api() missing 1 required positional argument: 'data'

Falsifying explicit example: test_api(
    case=Case(headers={'Authorization': 'Bearer ', 'X-KLM-ID': '...'}, query={'lastSeenBefore': '-PT2H', 'lastSeenAfter': 'PT2H', 'cloud': 'i-3bc4829309,42349c92'}),
    token_getter=<function run_schemathesis.token_getter.<locals>.retrieve_token>,
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 345, in execute_explicit_examples
    state.execute_once(
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 619, in execute_once
    result = self.test_runner(data, run)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/executors.py", line 52, in default_new_style_executor
    return function(data)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 615, in run
    return test(*args, **kwargs)
TypeError: test_api() missing 1 required positional argument: 'data'

Falsifying explicit example: test_api(
    case=Case(headers={'Authorization': 'Bearer ', 'X-KLM-ID': '...'}, query={'lastSeenBefore': 'P1D', 'lastSeenAfter': '-P1D', 'cloud': 'i-3bc4829309,42349c92'}),
    token_getter=<function run_schemathesis.token_getter.<locals>.retrieve_token>,
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 345, in execute_explicit_examples
    state.execute_once(
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 619, in execute_once
    result = self.test_runner(data, run)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/executors.py", line 52, in default_new_style_executor
    return function(data)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 615, in run
    return test(*args, **kwargs)
TypeError: test_api() missing 1 required positional argument: 'data'

Falsifying explicit example: test_api(
    case=Case(headers={'Authorization': 'Bearer ', 'X-KLM-ID': '...'}, query={'lastSeenBefore': '-P3DT4H5M0S', 'lastSeenAfter': 'PT4H500S', 'cloud': 'aws,azure:4975692a'}),
    token_getter=<function run_schemathesis.token_getter.<locals>.retrieve_token>,
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 345, in execute_explicit_examples
    state.execute_once(
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 619, in execute_once
    result = self.test_runner(data, run)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/executors.py", line 52, in default_new_style_executor
    return function(data)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 615, in run
    return test(*args, **kwargs)
TypeError: test_api() missing 1 required positional argument: 'data'

Falsifying explicit example: test_api(
    case=Case(headers={'Authorization': 'Bearer ', 'X-KLM-ID': '...'}, query={'lastSeenBefore': '2019-09-23T00:00:00.000Z', 'lastSeenAfter': '2019-09-23T00:00:00.000Z', 'cloud': 'aws'}),
    token_getter=<function run_schemathesis.token_getter.<locals>.retrieve_token>,
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 345, in execute_explicit_examples
    state.execute_once(
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 619, in execute_once
    result = self.test_runner(data, run)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/executors.py", line 52, in default_new_style_executor
    return function(data)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 615, in run
    return test(*args, **kwargs)
TypeError: test_api() missing 1 required positional argument: 'data'

Falsifying explicit example: test_api(
    case=Case(headers={'Authorization': 'Bearer ', 'X-KLM-ID': '...'}, query={'lastSeenBefore': '2019-09-23T12:02:01.700Z', 'lastSeenAfter': '2019-09-23T12:02:01.700Z', 'cloud': 'azure:42349c92,aws:i-3bc4829309'}),
    token_getter=<function run_schemathesis.token_getter.<locals>.retrieve_token>,
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 345, in execute_explicit_examples
    state.execute_once(
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 619, in execute_once
    result = self.test_runner(data, run)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/executors.py", line 52, in default_new_style_executor
    return function(data)
  File "/usr/local/lib/python3.8/dist-packages/hypothesis/core.py", line 615, in run
    return test(*args, **kwargs)
TypeError: test_api() missing 1 required positional argument: 'data'

```
I am not sure why I am getting so many of the same error messages, is it b/c Schemathesis is trying it multiple times to see if it succeeds even though it could be syntactically incorrect/not specified?

**Comment by Stranger6667** [comment]
> Not sure if this is correct?

To achieve the goal from the issue description I'd recommend randomly override generated data. Something like this:

```python
@schema.parametrize()
@schema.given(data=st.data())
def test_api(data, case, token_getter):
    ...  # edited for brevity
    if data.draw(st.booleans()):
        case.path_parameters["personId"] = "7dafa30d-25d9-4e1c-80b6-f842e8412f51"
```
In the example above, in 50% of cases, the `personId` parameter will have a generated value and in other 50% it will be explicitly set to `7dafa30d-25d9-4e1c-80b6-f842e8412f51`. You can tune the proportion with e.g. `if data.draw(st.integers(0, 9)) == 9` to have 10% chances of this condition succeed, etc.

> I am not sure why I am getting so many of the same error messages, is it b/c Schemathesis is trying it multiple times to see if it succeeds even though it could be syntactically incorrect/not specified?

The `schema.given` decorator works only on the function level, without any Open API parameters semantic. All arguments should be passed to the same decorator & included in the test function signature (I'll add an error message for such cases to avoid silent overriding):

```python
@schema.parametrize()
@schema.given(
    data=st.data(),
    personId=st.just("7dafa30d-25d9-4e1c-80b6-f842e8412f51"),
    managedAgentId=st.just("316e513d-bcf1-474f-8273-8c0e96f9bd4f"),
    managedAgent=st.just("316e513d-bcf1-474f-8273-8cf096f9bd4f")
)
...
def test_api(data, personId, managedAgentId, managedAgent, case, token_getter):
```

Otherwise, different `schema.given` override each other.

The `schema.parametrize` decorator creates multiple test instances from the same function affected by the problem above, then `pytest` runs all these generated tests and reports the same error for every test. I.e., it creates something like this (`given` is taken from Hypothesis here):

```python
@given(...)
def test_api_1(data, case)
    ...

@given(...)
def test_api_2(data, case)
```

**Comment by mbiuki** [comment]
Hi @Stranger6667,

## I)

Thanks for your guidance. I have fewer errors occurring based on the suggested improvements.

> Otherwise, different schema.given override each other.

I see.

> The schema.parametrize decorator creates multiple test instances from the same function affected by the problem above, then pytest runs all these generated tests and reports the same error for every test. I.e., it creates something like this (given is taken from Hypothesis here):

I see, thanks for elaborating.


## II)
Experimenting with the fixes, I have the following questions:
1. What is the job of `st.data()`? Does `st.data()` contain the attributes (key-value) of parsed OpenAPI YAML file? 
-  Using `st.data()` in `@schema.given()` annotation and passing it to the function `test_api` would pass attributes taken from the OpenAPI, right?
- So when we run `pytest testFile.py`, it starts calling that `test_api` function? 
- The `test_api` function is special for `pytest`, so it knows it has to look for such a function (`test_api`) name?

2. How can we pass more than one fixed uuid to `st.just()`, is there a way? e.g.,
`ids=st.just("b12b26e1-cb8c-4d72-8bdc-052aac79d981", "b12b26e1-cdfj-4d72-8bdc-052aac79d981")`
I get error for the above format.

Here is what I have so far:

```python
@settings(deadline=None) # disable the deadline completely.
@schema.parametrize()
@schema.given(
    data=st.data(),
    personId=st.just("7dafa30d-25d9-4e1c-80b6-f842e4412f51"),
    managedAgentId=st.just("316e513d-bcf1-174f-8273-8cfe96f9bd4f"),
    managedAgent=st.just("316e513d-bcf1-474f-8273-8cfe96f9bd4f"),
    userId=st.just("308051ea-8724-41ab-b22b-46dda920e2a6"),
    groupId=st.just("8537e5dc-0359-4af9-b88c-dcaf7b46376e"),
    alertId=st.just("b12b26e1-cb8c-4d72-8efc-052aac79d981"),
    ids=st.just("b12b26e1-cb8c-4d72-8bdc-003aac79d981"),
    groupKey=st.just("MSxFdmVudDo6RW5kcG9pbnQ6Ok5vdFByb3RlY3RlZCw1MTMs"),
    parentGroupId=st.just("8537e5dc-0359-4009-b88c-dcaf7b46376e")
    )
def test_api(data, \
             personId, \
             managedAgentId, \
             managedAgent, \
             userId, \
             groupId, \
             alertId, \
             ids, \
             groupKey, \
             parentGroupId, \
             case, \
             token_getter):
    token = token_getter()
    case.headers = case.headers or {}
    case.headers["Authorization"] = f"Bearer {token}"
    case.headers["X-KLM-ID"] = xklmid
    # the following are samples and must not be used, provide your own body fixed ids
    if data.draw(st.booleans()):
        case.path_parameters["personId"] = \
                                          "7dafa30d-25d9-4e1c-80b6-f842e4412f51"
        case.path_parameters["managedAgentId"] = \
                                          "316e513d-bcf1-474f-8273-8cfe96f9bd4f"
        case.path_parameters["managedAgent"] = \
                                          "316e513d-bcf1-474f-8273-8cfe96f9bd4f"
        case.path_parameters["userId"] = \
                                          "308051ea-8724-41ab-b22b-46dda920e2a6"
        case.path_parameters["groupId"] = \
                                          "8537e5dc-0359-4af9-b88c-dcaf7b46376e"
        case.path_parameters["alertId"] = \
                                          "b12b26e1-cb8c-4d72-8bdc-052aac79d981"
        case.path_parameters["ids"]  = data.draw(st.sampled_from([ \
                                       "b12b26e1-cb8c-4d72-8bdc-052aac79d981", \
                                       "8dc3ade9-e2af-4c47-9309-350aab23517d"]))
        case.path_parameters["groupKey"] = \
                              "MSxFdmVudDo6RW5kcG9pbnQ6Ok5vdFByb3RlY3RlZCw1MTMs"
        case.path_parameters["parentGroupId"] = \
                                          "8537e5dc-0359-4af9-b88c-dcaf7b46376e"
    case.call_and_validate()
```

- Should I remove all `case.path_parameters` in the function since we have `st.just()` or are they correlated?

## III)

1. It looks like I have 7 failures in my examples found in the open api yaml file, how can I find those errors to fix?

```
E       hypothesis.errors.MultipleFailures: Hypothesis found 7 failures in explicit examples.

run_schemathesis.py:144: MultipleFailures
--------------------------------------------------------------- Hypothesis ---------------------------------------------------------------
Falsifying explicit example: test_api(
    case=Case(headers={'Authorization': 'Bearer ', 'X-KLM-ID': 'e3e70682-c210-4cac-629f-6fbed82c07cd'}, query={'lastSeenBefore': 'PT200S', 'lastSeenAfter': '-PT200S', 'cloud': 'i-3bc4829309,42349c92'}),
    token_getter=<function run_schemathesis.token_getter.<locals>.retrieve_token>,
)
Traceback (most recent call last):
  File "/home/mehdi/.local/lib/python3.8/site-packages/hypothesis/core.py", line 345, in execute_explicit_examples
    state.execute_once(
  File "/home/mehdi/.local/lib/python3.8/site-packages/hypothesis/core.py", line 619, in execute_once
    result = self.test_runner(data, run)
  File "/home/mehdi/.local/lib/python3.8/site-packages/hypothesis/executors.py", line 52, in default_new_style_executor
    return function(data)
  File "/home/mehdi/.local/lib/python3.8/site-packages/hypothesis/core.py", line 615, in run
    return test(*args, **kwargs)
TypeError: test_api() missing 10 required positional arguments: 'data', 'personId', 'managedAgentId', 'managedAgent', 'userId', 'groupId', 'alertId', 'ids', 'groupKey', and 'parentGroupId'
```
I have 7 errors reporting above.

2. It looks like when the draw is true, something is not correct there:
 ```
    @settings(deadline=None) # disable the deadline completely.
    @schema.parametrize()
    @schema.given(
        data=st.data(),
        personId=st.just("7dafa30d-25d9-4e1c-80b6-f842e4412f51"),
        managedAgentId=st.just("316e513d-bcf1-474f-8273-8cfe96f9bd4f"),
        managedAgent=st.just("316e513d-bcf1-474f-8273-8cfe96f9bd4f"),
        userId=st.just("308051ea-8724-41ab-b22b-46dda920e2a6"),
        groupId=st.just("8537e5dc-0359-4af9-b88c-dcaf7b46376e"),
        alertId=st.just("b12b26e1-cb8c-4d72-8bdc-052aac79d981"),
        ids=st.just("b12b26e1-cb8c-4d72-8bdc-052aac79d981"),
        groupKey=st.just("MSxFdmVudDo6RW5kcG9pbnQ6Ok5vdFByb3RlY3RlZCw1MTMs"),
        parentGroupId=st.just("8537e5dc-0359-4af9-b88c-dcaf7b46376e")
        )
    def test_api(data, \
                 personId, \
                 managedAgentId, \
                 managedAgent, \
                 userId, \
                 groupId, \
                 alertId, \
                 ids, \
                 groupKey, \
                 parentGroupId, \
                 case, \
                 token_getter):
        token = token_getter()
        case.headers = case.headers or {}
        case.headers["Authorization"] = f"Bearer {token}"
        case.headers["X-KLM-ID"] = xklmid
        # the following are samples and must not be used, provide your own body fixed ids
        if data.draw(st.booleans()):
>           case.path_parameters["personId"] = \
                                              "7dafa30d-25d9-4e1c-80b6-f842e4412f51"
E           TypeError: 'NoneType' object does not support item assignment

run_schemathesis.py:175: TypeError
--------------------------------------------------------------- Hypothesis ---------------------------------------------------------------
Falsifying example: test_api(
    data=data(...),
    personId='7dafa30d-25d9-4e1c-80b6-f842e4412f51',
    managedAgentId='316e513d-bcf1-474f-8273-8cfe96f9bd4f',
    managedAgent='316e513d-bcf1-474f-8273-8cfe96f9bd4f',
    userId='308051ea-8724-41ab-b22b-46dda920e2a6',
    groupId='8537e5dc-0359-4af9-b88c-dcaf7b46376e',
    alertId='b12b26e1-cb8c-4d72-8bdc-052aac79d981',
    ids='b12b26e1-cb8c-4d72-8bdc-052aac79d981',
    groupKey='MSxFdmVudDo6RW5kcG9pbnQ6Ok5vdFByb3RlY3RlZCw1MTMs',
    parentGroupId='8537e5dc-0359-4af9-b88c-dcaf7b46376e',
    case=Case(headers={'Authorization': 'Bearer ', 'X-KLM-ID': 'e3e70682-c009-4cac-629f-6fbed82c07cd'}, query={}),
    token_getter=<function run_schemathesis.token_getter.<locals>.retrieve_token>,
)
Draw 1: True
```

**Comment by Stranger6667** [comment]
Hi @mbiuki 

> Thanks for your guidance. I have fewer errors occurring based on the suggested improvements.

You are very welcome!

> What is the job of st.data()? Does st.data() contain the attributes (key-value) of parsed OpenAPI YAML file?
> Using st.data() in @schema.given() annotation and passing it to the function test_api would pass attributes taken from the OpenAPI, right?

It is [a special Hypothesis strategy](https://hypothesis.readthedocs.io/en/latest/data.html#drawing-interactively-in-tests) that allows you to draw values interactively in tests. There is no Open API semantics there.

> So when we run pytest testFile.py, it starts calling that test_api function?

Yes, at some point, it uses this function body to run all tests generated by `schema.parametrize`.

> The test_api function is special for pytest, so it knows it has to look for such a function (test_api) name?

Right! Pytest collects all generated tests under different names (they are extended to something like `test_api[POST /users/]`) and then runs them.

> How can we pass more than one fixed uuid to st.just(), is there a way? e.g.,
ids=st.just("b12b26e1-cb8c-4d72-8bdc-052aac79d981", "b12b26e1-cdfj-4d72-8bdc-052aac79d981")
I get error for the above format.

If you'd like to randomly use one of these values, then `st.sampled_from` will work. If you need a list or a tuple then you need to wrap the values to a single argument for `st.just` -  `ids=st.just(("b12b26e1-cb8c-4d72-8bdc-052aac79d981", "b12b26e1-cdfj-4d72-8bdc-052aac79d981"))`

> Should I remove all case.path_parameters in the function since we have st.just() or are they correlated?

Those are indeed different ways to achieve the same goal. You need to either draw interactively in tests with `data.draw` which is provided by the `st.data()` strategy, or pass all those extra values as strategies via `schema.given`. This approach is more convenient if you have some complex data generation strategy that is too complex to keep inside the test body. For single values, it might be simpler to set them directly without adding a new argument to `schema.given`.

Still, `schema.given` only provides a way to use generated values within a test - you still have to modify `case`.

> It looks like I have 7 failures in my examples found in the open api yaml file, how can I find those errors to fix?

Could you please share a bit more here? I can't reproduce this `TypeError` locally, but it seems to be related to the setup & the way tests are executed. I'd appreciate the test file content & at least partial schema.

> It looks like when the draw is true, something is not correct there:

I assume that this function is used for multiple different API endpoints (there are no `endpoint` or `method` filters in `schema.parametrize`), and some of them have no path parameters - you need to set the right condition of when those parameters should be added to `case`. For example:

```python
...
def test_api(...):
    ...
    if (case.method, case.path) == ("GET", "/users/{personId}/") and data.draw(st.booleans()):
        case.path_parameters["personId"] = "..."
```

Thank you for asking these questions! I'd be happy to elaborate.

**Comment by Stranger6667** [comment]
Closing it as it is exactly what the coverage phase does
