### ISSUE TITLE
[FEATURE] add option not to verify TLS certificate in `replay` mode

### ISSUE THREAD

**Issue by niya3** [schemathesis/schemathesis#1395]
**Is your feature request related to a problem? Please describe.**
When i'm saving VCR cassette to reproduce some intriguing request i'm not able to re-run them because of self-signed cert used on the site:

```
$ schemathesis replay cassette.yaml --id 1
Replaying cassette: cassette.yaml
Total interactions: N

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/venv/lib/python3.10/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)
...
```

Unfortunately, same option as in `run` mode isn't supported

```
$ schemathesis replay cassette.yaml --id 1 --request-tls-verify 
Usage: schemathesis replay [OPTIONS] CASSETTE_PATH
Try 'schemathesis replay -h' for help.

Error: No such option: --request-tls-verify 
```

**Describe the solution you'd like**
Add the site self-signed cert to the system.

**Describe alternatives you've considered**
Save additional info in VCR cassette and use it in `replay` mode to decide whether TLS verify is required or not (?)

**Comment by Stranger6667** [comment]
Thanks! Will add soon

**Comment by Stranger6667** [comment]
> Save additional info in VCR cassette and use it in replay mode to decide whether TLS verify is required or not (?)

Nice feature to be used as a default, when nothing is specified explicitly

**Comment by Stranger6667** [comment]
I think it could be even a part of #1143 - there are a few things I wanted to add to cassettes anyway.
