### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by dil-gfischhof** [schemathesis/schemathesis#1409]
Hi Folks,

I would like to test a program which has microservices architecture.
It means that it has several APIs (one for every service), I would like to test them all.
And would like to create such many decorated functions, are the same.
Like this:

```
a_schema = schemathesis.from_...
b_schema = schemathesis.from_...
# ...
@a_schema.parametrize()
def test_a(case):
    case.call_and_validate()

@b_schema.parametrize()
def test_b(case):
    case.call_and_validate()

```
Question:
How can I generate tests from several APIs.

I would like to put them into a list, and process the list:

```
schemas = [a_schema, b_schema, ...]
@some_decorator_if_needed
def test_my_app(case):
    somehow_test_all_apis()
```

BR,
George

**Comment by Stranger6667** [comment]
Hello George,

Thank you for asking! :) At the moment there is no built-in way to shortcut this process.
You could do something like this, to generate multiple test functions (though it is not quite handy):

```python
import schemathesis

schemas = [
    schemathesis.from_uri("https://example.schemathesis.io/openapi.json", validate_schema=False),
    schemathesis.from_uri("https://example.schemathesis.io/openapi.json", validate_schema=False)
]


for idx in range(len(schemas)):
    exec(f"""
@schemas[{idx}].parametrize()
def test_{idx}(case):
    case.call_and_validate()
    """)
```

Personally, I don't particularly like code generation like this, but I think it is a good use case to be added to the core library.

**Comment by dil-gfischhof** [comment]
Hi @Stranger6667 

I tried it, and it has a syntax error ;)

```
Traceback (most recent call last):
  File "test_doc_conformance.py", line 101, in <module>
    exec(f"""
  File "<string>", line 2
    @schemas[0].parametrize()
            ^
SyntaxError: invalid syntax
```

but the following works:
```

for index in range(len(schemas)):
    exec(f"""
schema=schemas[{index}]
@schema.parametrize()
def test_{index}(case):
    case.headers = headers
    case.call_and_validate()
    """)
```

I think it should be added into documentation into a chapter titled Microservices
I will go forward with links, so perhaps other useful things can be put into that chapter. (I would like to test consume a data which is added from one service from a different one - user journey)

**Comment by Stranger6667** [comment]
> I tried it, and it has a syntax error ;)

Oh, I forgot that it is Python 3.9+ version only. You are exactly right about the version you provided.

Yep, it definitely should go to the docs. Though, I might want to prototype a more common solution first, so such a use case is directly supported without workarounds :)

I'll try to respond in #1405 during this week as well, so we can have more ideas on how to improve the status quo.

Btw. Thank you for bringing all these topics, it helps a lot!

**Comment by Stranger6667** [comment]
There is a fundamental difference between how Hypothesis and pytest work, and many quirks come from there (see https://github.com/pytest-dev/pytest/issues/916 for details). Hypothesis implies a feedback loop between generated samples and how the test function behaves, so it adjusts the data generation to enable shrinking and better test space exploration - i.e. it might decide that a certain direction is not interesting and avoid exploring it and explore others instead. On the other hand, pytest loads all collected test functions & evaluates parameters upfront (unless it is called via `request.getfixturevalue` in the test body).

Generating the test cases upfront would defeat the purpose of Hypothesis and all the great features like shrinking / targeted testing. It is still possible to generate cases manually (similarly to [what](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/strategies/_internal/strategies.py#L271) `strategy.example()` does), collect them into a list and then pass them to `pytest.parametrize`. There are also underlying methods that could be used to create those Hypothesis tests separately + Hypothesis strategies could be pulled out (so they could be used with e.g. `unittes`).

There surely could be more straightforward/convenient ways of combining Hypothesis property-based tests with regular pytest ones, but I think that the abovementioned integration issue should be solved first.

> To use the list of APIs a parametrize(schemas: list) function would be good.

The current implementation generates a set of test functions where each one is a Hypothesis test for a specific endpoint. Maybe, the following will work as an extension of the current `parametrize`?

```python
import schemathesis

s1 = schemathesis.from_dict({...})
s2 = schemathesis.from_uri("...")
s3 = schemathesis.from_path("...")

@schemathesis.parametrize(s1, s2, s3)
def test(case):
    ...
```

So, different loaders are supported. Or maybe some shortcuts could be possible as well if there could be just a single loader:

```python
import schemathesis

@schemathesis.parametrize({}, {}, {}, loader=schemathesis.from_dict)
def test(case):
    ...
```

**Comment by Stranger6667** [comment]
> Also it could use the stateful variant by default.

Could be, yep. Or at least there could be an argument to they hypothetical `schemathesis.parametrize` that controls this behavior

**Comment by dil-gfischhof** [comment]
> ```python
> @schemathesis.parametrize(s1, s2, s3, stateful=True)
> def test(case):
>     ...
> ```

I like it :) specially as s1,s2,s3 can be a list (I saw once a microservice where there were 52 APIs, right now I test a microservice with only 12 APIs) 
This form is also good, because it uses the previously created schemas. It can be useful, for example because I can load schemas from different places (URL, file), also for the URLs I can use different parameters (for example verify)

**Comment by Stranger6667** [comment]
> Maybe I am wrong, but as I see schemathesis does not need so deep integration, because it has just a very specific target, the APIs.
> So it would not need those specific setups and teardowns.

All Schemathesis tests are effectively Hypothesis tests, therefore they have the same integration issues regardless of their testing scope. In the aspect of data generation, Hypothesis and pytest have completely different approaches, so using Hypothesis in the way it is not supposed to be used deflects its benefits.

I'd agree, that `schema.parametrize` does quite much stuff that is implicit, but it solves (somehow) the integration between schema-based generated Hypothesis tests and pytest's parametrization mechanisms.

`@schema.parametrize()` is a rough equivalent of the code below, but without a nesting layer visible to the end-user:

```python
@pytest.mark.parametrize("endpoint", schema.get_all_operations())
def test_api(endpoint):

    @given(endpoint.as_strategy())
    def test_endpoint(case):
        ...

    test_endpoint()
```

Schemathesis generates a set of Hypothesis tests with strategies derived from the API schema. So, it is supposed to be used in workflows of Hypothesis tests, and separate functions for data generation are discouraged, as they imply no feedback loop with the fuzzer, which is essential for property-based tests. Therefore the absence of such a function in the public API is intentional.

> I can imagine it as a simple function inside the test. And it creates the cases as it needs.

It is possible if the test is a Hypothesis test:

```python
from hypothesis import given, strategies as st

import schemathesis

schema = schemathesis.from_uri(
    "https://example.schemathesis.io/openapi.json",
    validate_schema=False
)

@given(data=st.data())
def test_crud(data):
    create_user = data.draw(schema["/users/"]["POST"].as_strategy())
```

For data generation, separate from Hypothesis tests, the following could be used:

```python
import hypothesis
import pytest

import schemathesis


def generate_examples(strategy, max_examples=100):
    @hypothesis.given(strategy)
    @hypothesis.settings(
        database=None,
        max_examples=max_examples,
        deadline=None,
        verbosity=hypothesis.Verbosity.quiet,
        phases=(hypothesis.Phase.generate,),
        suppress_health_check=hypothesis.HealthCheck.all(),
    )
    def example_generating_inner_function(ex):
        examples.append(ex)

    examples = []
    example_generating_inner_function()
    return examples


schema = schemathesis.from_uri(
    "https://example.schemathesis.io/openapi.json",
    validate_schema=False
)

create_user = schema["/users/"]["POST"].as_strategy()


@pytest.mark.parametrize("case", generate_examples(create_user))
def test_something(case):
    ...
```

> The only thing that is important, to report it. And for that purpose pytest's report hook could be used. Or just add the result to result collection

That comes from the Hypothesis [pytest plugin](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/_hypothesis_pytestplugin.py) and is already in place.

So, I would consider Schemathesis tests more like a kind of Hypothesis tests rather than a separate thing, because it is built on top of it and utilizes all the main mechanisms from there.
