### ISSUE TITLE
Getting errors while trying out schemathesis.

### ISSUE THREAD

**Issue by h-barthwal** [schemathesis/schemathesis#1591]
I installed `schemathesis` using `pip3 install schemathesis` and tried it out as follows:

```bash
$ st run http://localhost:8000/graphql  --show-errors-tracebacks
/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/hypothesis/errors.py:127: HypothesisDeprecationWarning: MultipleFailures is deprecated; use the builtin `BaseExceptionGroup` type instead, or `exceptiongroup.BaseExceptionGroup` before Python 3.11
  note_deprecation(
============================================================================= Schemathesis test session starts =============================================================================
Schema location: http://localhost:8000/graphql
Base URL: http://localhost:8000/graphql
Specification version: GraphQL
Workers: 1
Collected API operations: 4

MyQuery.resolverOne /home/hbarthwal/mypython-venv/lib/python3.8/site-packages/hypothesis/errors.py:127: HypothesisDeprecationWarning: MultipleFailures is deprecated; use the builtin `BaseExceptionGroup` type instead, or `exceptiongroup.BaseExceptionGroup` before Python 3.11
  note_deprecation(
E                                                                                                                                                        [ 25%]
MyQuery.resolverTwo /home/hbarthwal/mypython-venv/lib/python3.8/site-packages/hypothesis/errors.py:127: HypothesisDeprecationWarning: MultipleFailures is deprecated; use the builtin `BaseExceptionGroup` type instead, or `exceptiongroup.BaseExceptionGroup` before Python 3.11
  note_deprecation(
E                                                                                                                                               [ 50%]
MyQuery.resolverThree /home/hbarthwal/mypython-venv/lib/python3.8/site-packages/hypothesis/errors.py:127: HypothesisDeprecationWarning: MultipleFailures is deprecated; use the builtin `BaseExceptionGroup` type instead, or `exceptiongroup.BaseExceptionGroup` before Python 3.11
  note_deprecation(
E                                                                                                                                                     [ 75%]
MyQuery.resolverFour /home/hbarthwal/mypython-venv/lib/python3.8/site-packages/hypothesis/errors.py:127: HypothesisDeprecationWarning: MultipleFailures is deprecated; use the builtin `BaseExceptionGroup` type instead, or `exceptiongroup.BaseExceptionGroup` before Python 3.11
  note_deprecation(
E                                                                                                                                                          [100%]

========================================================================================== ERRORS ==========================================================================================
_____________________________________________________________________________ MyQuery.resolverOne [P] _____________________________________________________________________________
Traceback (most recent call last):
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/runner/impl/core.py", line 307, in run_test
    test(checks, targets, result, errors=errors, headers=headers, **kwargs)
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/runner/impl/core.py", line 570, in network_test
    case: Case,
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/hypothesis/core.py", line 1257, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/specs/graphql/schemas.py", line 208, in get_case_strategy
    strategy = {
KeyError: 'MyQuery'

________________________________________________________________________ MyQuery.resolverTwo [P] _________________________________________________________________________
Traceback (most recent call last):
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/runner/impl/core.py", line 307, in run_test
    test(checks, targets, result, errors=errors, headers=headers, **kwargs)
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/runner/impl/core.py", line 570, in network_test
    case: Case,
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/hypothesis/core.py", line 1257, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/specs/graphql/schemas.py", line 208, in get_case_strategy
    strategy = {
KeyError: 'MyQuery'

___________________________________________________________________________ MyQuery.resolverThree [P] ____________________________________________________________________________
Traceback (most recent call last):
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/runner/impl/core.py", line 307, in run_test
    test(checks, targets, result, errors=errors, headers=headers, **kwargs)
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/runner/impl/core.py", line 570, in network_test
    case: Case,
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/hypothesis/core.py", line 1257, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/specs/graphql/schemas.py", line 208, in get_case_strategy
    strategy = {
KeyError: 'MyQuery'

______________________________________________________________________________ MyQuery.resolverFour [P] ______________________________________________________________________________
Traceback (most recent call last):
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/runner/impl/core.py", line 307, in run_test
    test(checks, targets, result, errors=errors, headers=headers, **kwargs)
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/runner/impl/core.py", line 570, in network_test
    case: Case,
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/hypothesis/core.py", line 1257, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/hbarthwal/mypython-venv/lib/python3.8/site-packages/schemathesis/specs/graphql/schemas.py", line 208, in get_case_strategy
    strategy = {
KeyError: 'MyQuery'


If you need assistance in solving this, feel free to join our Discord server and report it:

  https://discord.gg/R9ASRAmHnA

========================================================================================= SUMMARY ==========================================================================================

No checks were performed.

Hint: You can visualize test results in Schemathesis.io by using `--report` in your CLI command.

==================================================================================== 4 errored in 0.07s ====================================================================================
```
Can someone tell me how to fix these errors?

**Comment by Stranger6667** [comment]
Hi @h-barthwal !

Thank you for reporting! Could you, please share your GraphQL spec? I assume this is a bug inside Schemathesis as it assumes that the `Query` type is always named `Query`

**Comment by h-barthwal** [comment]
@Stranger6667 I cannot exactly share my schema (and I have already renamed a few things in the above output) as it is owned by my employer. But yes, the root Query type in my schema is not named as `Query`. The full schema is too big to share here and I will have to basically rename everything in there. But my schema basically looks like this at the root level:

```graphql
type MyQuery { 
  resolverOne : TypeOne!
  resolverTwo : TypeTwo!
  resolverThree : TypeThree!
  resolverFour : TypeFour!
}
```

I hope that helps.

**Comment by Stranger6667** [comment]
Thanks! I'll take a look at how it could be automatically detected then

**Comment by Stranger6667** [comment]
Could you, please, share how you define that some custom type should work as `Query` instead? I.e. how the parser will detect that type `T` is the `Query` type

**Comment by Stranger6667** [comment]
This behavior will be fixed in the next release, thank you once again for reporting!

**Comment by h-barthwal** [comment]
@Stranger6667 Thanks for the quick follow up here. Eager to try `schemathesis` out once this is fixed.

**Comment by Stranger6667** [comment]
I am absolutely delighted to fix it! Curious about your feedback when you'll have a chance to try it :)
