### ISSUE TITLE
[FEATURE] Handle ChunkedEncodingError and add it to a result report

### ISSUE THREAD

**Issue by avrazheva** [schemathesis/schemathesis#1600]
**Is your feature request related to a problem? Please describe.**
Для некоторых ручек сервисов получаем ошибку:
```
Traceback (most recent call last):
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/urllib3/response.py", line 700, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/urllib3/response.py", line 441, in _error_catcher
    yield
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/urllib3/response.py", line 767, in read_chunked
    self._update_chunk_length()
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/urllib3/response.py", line 704, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/requests/models.py", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/urllib3/response.py", line 575, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/urllib3/response.py", line 796, in read_chunked
    self._original_response.close()
  File "/Users/anrazheva/.pyenv/versions/3.9.6/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/urllib3/response.py", line 458, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/schemathesis/runner/impl/core.py", line 599, in network_test
    response = _network_test(
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/schemathesis/runner/impl/core.py", line 656, in _network_test
    response = case.call(**kwargs)
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/schemathesis/models.py", line 325, in call
    response = session.request(**data)  # type: ignore
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/requests/sessions.py", line 687, in send
    r.content
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/requests/models.py", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/anrazheva/Documents/automation/boucle/.venv/lib/python3.9/site-packages/requests/models.py", line 763, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

**Describe the solution you'd like**
Кажется, что во время запуска теста теряем коннекшн к сервису. Можно сделать какой-то хендлинг этого события и выводить отдельным пунктом в репорт.

**Comment by Stranger6667** [comment]
I think that the main issue here would be the ability to reproduce such a problem in our test suite, preferably without mocking.
