### ISSUE TITLE
[BUG]stratup fail caused by dependencies,update werkzeug(2.0.2 -> 2.2.2),No module named 'werkzeug.wrappers.json'

### ISSUE THREAD

**Issue by devicehzy** [schemathesis/schemathesis#1619]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
update werkzeug,the following error occurred  
```
No module named 'werkzeug.wrappers.json'
```

**To Reproduce**
1.Set poetry dependencies and install it
```
[tool.poetry.dependencies]
python = "^3.8.0"
schemathesis = "3.10.0"
```
2.show poetry install pkg  
```
> poetry show
```
![image](https://user-images.githubusercontent.com/92512639/194686314-3b2da41a-27fb-48ef-9e87-854eea1ac749.png)  
3.run  
```
Traceback (most recent call last):
  File "./x/xx.py", line 40, in <module>
    check_operation(MODULE_PATH)
  File "./x/xx.py", line 27, in check_operation
    for sub_pkg in list_module(module_path):
  File "./x/xx.py", line 12, in list_module
    path = importlib.import_module(module_path).__path__
  File "/root/.pyenv/versions/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./x/xx.py", line 1, in <module>
    import schemathesis
  File "/builds/xx/xx/.venv/lib/python3.8/site-packages/schemathesis/__init__.py", line 7, in <module>
    from . import fixups, hooks, runner, serializers, targets
  File "/builds/xx/xx/.venv/lib/python3.8/site-packages/schemathesis/fixups/__init__.py", line 3, in <module>
    from . import fast_api
  File "/builds/xx/xx/.venv/lib/python3.8/site-packages/schemathesis/fixups/fast_api.py", line 3, in <module>
    from ..hooks import HookContext, register, unregister
  File "/builds/xx/xx/.venv/lib/python3.8/site-packages/schemathesis/hooks.py", line 10, in <module>
    from .utils import GenericResponse, deprecated_property
  File "/builds/xx/xx/.venv/lib/python3.8/site-packages/schemathesis/utils.py", line 39, in <module>
    from werkzeug.wrappers.json import JSONMixin
ModuleNotFoundError: No module named 'werkzeug.wrappers.json'
```

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Windows
 - Python version:  3.8.0
 - Schemathesis version: 3.10.0

**Additional context**

**Comment by Stranger6667** [comment]
Hi!

> Schemathesis version: 3.10.0

You use a quite outdated Schemathesis version. The issue has been solved a while ago.
