### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alenaqa5** [schemathesis/schemathesis#1665]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**

**To Reproduce**

1. Run this command '.schemathesis run ... --request-tls-verify=no..'
2. See error
An internal error happened during a test run

Error: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/schemathesis/cli/__init__.py", line 872, in into_event_stream
    loaded_schema = load_schema(config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/schemathesis/cli/__init__.py", line 909, in load_schema
    return _try_load_schema(config, first, second)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/schemathesis/cli/__init__.py", line 919, in _try_load_schema
    return second(config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/schemathesis/cli/__init__.py", line 928, in _load_graphql_schema
    return loader(config.schema_location, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/schemathesis/specs/graphql/loaders.py", line 89, in from_url
    decoded = response.json()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Please, consider reporting the traceback below it to our issue tracker: https://github.com/schemathesis/schemathesis/issues/new?labels=Status%3A+Review+Needed%2C+Type%3A+Bug&template=bug_report.md&title=%5BBUG%5D

If possible, please post a minimal version of your API schema that cause this behavior:

```yaml
{
    "openapi": "3.0.2"
    ... Add more here
}
```

**Expected behavior**
I thought this command will launch tests 

**Environment (please complete the following information):**

- OS: [MacOs]
- Python version: [e.g. 3.10.4]
- Schemathesis version: [schemathesis-3.17.5]
- Spec version: [e.g. Open API 3.0.2]

**Additional context**

**Comment by Stranger6667** [comment]
Hi!

Could you please, add more details? E.g. the full command that you used and your schema (if possible). At the first glance it looks like your backend (if you go over network) return an invalid YAML / JSON file

**Comment by Stranger6667** [comment]
The newer version of Schemathesis provides a much more concise error description for such scenarios - the issue is not specific to Schemathesis itself, but to the fact the user tries to load a schema that is in a not supported format.
