### ISSUE TITLE
[BUG] --report flag without arguments is broken.

### ISSUE THREAD

**Issue by phknot** [schemathesis/schemathesis#1753]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
When running from the CLI with the --report flag an error is thrown. When adding any arguments like true or 1, a file with that name is created. I would like a report on schemathesis.io to be generated.

**To Reproduce**

Run a valid schemathesis command with the --report flag

The error received is the following:
```
Traceback (most recent call last):
  File "/home/docker/.local/bin/st", line 8, in <module>
    sys.exit(schemathesis())
  File "/home/docker/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/docker/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/docker/.local/lib/python3.8/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/docker/.local/lib/python3.8/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/home/docker/.local/lib/python3.8/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/docker/.local/lib/python3.8/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/docker/.local/lib/python3.8/site-packages/click/core.py", line 2356, in process_value
    value = self.type_cast_value(ctx, value)
  File "/home/docker/.local/lib/python3.8/site-packages/click/core.py", line 2344, in type_cast_value
    return convert(value)
  File "/home/docker/.local/lib/python3.8/site-packages/click/core.py", line 2316, in convert
    return self.type(value, param=self, ctx=ctx)
  File "/home/docker/.local/lib/python3.8/site-packages/click/types.py", line 83, in __call__
    return self.convert(value, param, ctx)
  File "/home/docker/.local/lib/python3.8/site-packages/click/types.py", line 712, in convert
    lazy = self.resolve_lazy_flag(value)
  File "/home/docker/.local/lib/python3.8/site-packages/click/types.py", line 694, in resolve_lazy_flag
    if os.fspath(value) == "-":
TypeError: expected str, bytes or os.PathLike object, not object
```

**Expected behavior**
--report with no flags should upload a report to schemathesis.io

**Environment (please complete the following information):**

- OS: Debian WSL
- Python version: 3.8.10
- Schemathesis version: 3.19.5
- Spec version: 3.0.3

**Comment by dd-ssc** [comment]
Same issue here, different environment:

- OS: macOS 13.4.1
- Python version: 3.10.12
- Schemathesis version: 3.19.5
- Spec version: no idea

I've been trying out schemathesis first time today, followed the instructions to the letter and encountered this uncaught exception. Guess I'll stop trying.

**Comment by Stranger6667** [comment]
For reference - the exception happens with ‘click’ > 8.1.3 (starting from [this](https://github.com/pallets/click/commit/43c2e7f331e78684d2549439c3338335f0ddb854) commit). Schemathesis relied on previous behaviour in order to support both variants of using this CLI option, with and without a value. I am going to work on a fix somewhere next week when I am back from vacation, a temporary solution could be to pin the ‘click’ version to 8.1.3.

**Comment by phknot** [comment]
Thanks for fixing, now my other devs don't need to bug me to read the logs for them anymore when they break the spec again ;D
