### ISSUE TITLE
[BUG] Fail to run CLI. Getting KeyError: 'location'

### ISSUE THREAD

**Issue by tsyg** [schemathesis/schemathesis#1768]
**Checklist**

- [ ] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [ ] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

Having schemathesis installed and logged in via ```st auth login __MY_TOKEN__``` 
I keep having the same error when playing with CLI (using gitbash  under windows): ```KeyError: 'location'```
I've set schema URL to https://petstore3.swagger.io/api/v3/openapi.json - still the same.
Did I miss anything - or this is a bug?

**To Reproduce**

Run the command below, see error message
<pre>
$ st run tinytest --checks=all --report
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\st.exe\__main__.py", line 7, in <module>
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\schemathesis\cli\__init__.py", line 727, in run
    details = client.get_api_details(name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\schemathesis\service\client.py", line 50, in get_api_details
    return ApiDetails(location=data["location"], base_url=data["base_url"])
                               ~~~~^^^^^^^^^^^^
KeyError: 'location'
</pre>

If possible, please post a minimal version of your API schema that cause this behavior:

The error seems to happen regardless the OpenAPI specification.
e.g. sample one https://petstore3.swagger.io/api/v3/openapi.json
https://raw.githubusercontent.com/tsyg/tgen/poc_via_open_ai/tiny_api01.yml

**Expected behavior**
Meaningful output: tests, results.. (not sure - I'm first time running it)

**Environment :**

- OS:  Windows
- Python version: 3.11
- Schemathesis version: st, version 3.19.6
- Spec version: https://petstore3.swagger.io/api/v3/openapi.json

**Additional context**
Add any other context about the problem here.

**Comment by tsyg** [comment]
Having schemathesis installed and logged in via ```st auth login __MY_TOKEN__``` 
I keep having the same error when playing with CLI (using gitbash  under windows): ```KeyError: 'location'```
I've set schema URL to https://petstore3.swagger.io/api/v3/openapi.json - still the same.
Did I miss anything - or this is a bug?

<pre>
$ st run tinytest --checks=all --report
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\st.exe\__main__.py", line 7, in <module>
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\schemathesis\cli\__init__.py", line 727, in run
    details = client.get_api_details(name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsyg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\schemathesis\service\client.py", line 50, in get_api_details
    return ApiDetails(location=data["location"], base_url=data["base_url"])
                               ~~~~^^^^^^^^^^^^
KeyError: 'location'

</pre>

**Comment by Stranger6667** [comment]
Thanks for reporting! It is a bug, will fix it this evening

**Comment by Stranger6667** [comment]
Fixed on the SaaS side. Thanks again and sorry for inconvenience
