### ISSUE TITLE
[BUG] Schemathesis crashes when using experimental features

### ISSUE THREAD

**Issue by ahmayun** [schemathesis/schemathesis#2353]
### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug
Running experimental features with the `--debug-output-file` option causes schemathesis to crash with `Object of type ... is not JSON serializable` errors. If I remove the `--debug-output-file` cli option it runs fine.
Clearly describe the issue you're facing.

### To Reproduce

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:
1. Just run the following command:
```
st run \
  --debug-output-file debug-logs/my-debug-log.json \
  --hypothesis-max-examples 1 \
  --base-url <your-url> \
  --stateful links \
  --experimental=stateful-test-runner \
  <any-schema>
```
2. Gives:
```
Internal Error

Schemathesis encountered an unexpected issue.

Traceback (most recent call last):
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/schemathesis/cli/__init__.py", line 1514, in execute
    handler.handle_event(execution_context, event)
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/schemathesis/cli/debug.py", line 23, in handle_event
    stream.write(json.dumps(data))
                 ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type StateMachineMeta is not JSON serializable

We apologize for the inconvenience. This appears to be an internal issue.
Please consider reporting this error to our issue tracker:

  https://github.com/schemathesis/schemathesis/issues/new?labels=Status%3A%20Needs%20Triage%2C+Type%3A+Bug&template=bug_report.md&title=%5BBUG%5D.
Traceback (most recent call last):
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/bin/st", line 8, in <module>
    sys.exit(schemathesis())
             ^^^^^^^^^^^^^^
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/schemathesis/cli/__init__.py", line 1022, in run
    execute(
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/schemathesis/cli/__init__.py", line 1514, in execute
    handler.handle_event(execution_context, event)
  File "/Users/ahmayun/internship/brazil-ws-apifuzzer/venv/lib/python3.12/site-packages/schemathesis/cli/debug.py", line 23, in handle_event
    stream.write(json.dumps(data))
                 ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type StateMachineMeta is not JSON serializable
```
3. A similar issue will occur for `--experimental=schema-analysis`

This schema should be sufficient:

```yaml
openapi: 3.0.0
info:
  title: Minimal OpenAPI 3.0 Example
  description: A minimal OpenAPI 3.0 YAML file example
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Retrieves a greeting message
      responses:
        '200':
          description: A successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello, World!
```

### Expected behavior

Shouldn't crash.

### Environment

```
- OS: macOS 14.4.1 (23E224) (M3 Pro)
- Python version: 3.12.4
- Schemathesis version: 3.32.0
- Spec version: 3.0.0
```

### Additional context

Include any other relevant details, like logs or screenshots.

**Comment by Stranger6667** [comment]
Thank you so much for reporting! The fix is available in `3.32.2`
