### ISSUE TITLE
[BUG] jsonschema.exceptions.ValidationError: 'query' is not one of ['body'] when testing test_server.sh

### ISSUE THREAD

**Issue by ZanderChang** [schemathesis/schemathesis#804]
I run the `test_server.sh` as mentioned in `CONTRIBUTING.rst` and test with `schemathesis`, but it just raises an error.

```sh
➜  ~ schemathesis run --stateful=links --checks all http://0.0.0.0:8081/schema.yaml --show-errors-tracebacks
An internal error happened during a test run
Error: Traceback (most recent call last):
  File "/home/zhang/.local/lib/python3.7/site-packages/schemathesis/runner/__init__.py", line 186, in execute_from_schema
    operation_id=operation_id,
  File "/home/zhang/.local/lib/python3.7/site-packages/schemathesis/runner/__init__.py", line 341, in load_schema
    **loader_options,
  File "/home/zhang/.local/lib/python3.7/site-packages/schemathesis/loaders.py", line 88, in from_uri
    skip_deprecated_endpoints=skip_deprecated_endpoints,
  File "/home/zhang/.local/lib/python3.7/site-packages/schemathesis/loaders.py", line 121, in from_file
    skip_deprecated_endpoints=skip_deprecated_endpoints,
  File "/home/zhang/.local/lib/python3.7/site-packages/schemathesis/loaders.py", line 141, in from_dict
    _maybe_validate_schema(raw_schema, definitions.SWAGGER_20, validate_schema)
  File "/home/zhang/.local/lib/python3.7/site-packages/schemathesis/loaders.py", line 175, in _maybe_validate_schema
    jsonschema.validate(instance, schema)
  File "/home/zhang/.local/lib/python3.7/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'query' is not one of ['body']

Failed validating 'enum' in schema[0]['properties']['in']:
    {'description': 'Determines the location of the parameter.',
     'enum': ['body'],
     'type': 'string'}

On instance['in']:
    'query'

Add this option to your command line parameters to see full tracebacks: --show-errors-tracebacks

You can disable input schema validation with --validate-schema=false command-line option
In this case, Schemathesis cannot guarantee proper behavior during the test run
➜  ~ schemathesis --version
schemathesis, version 2.6.0

```

**Comment by Stranger6667** [comment]
Hi @ZanderChang!

I think that this behavior is confusing indeed. However, it is expected. The generated schema contains invalid endpoints (e.g. `/api/invalid`), and Schemathesis refuses to run tests against it. I added them to test Schemathesis's behavior in such cases.

Indeed, the test server's default configuration doesn't follow the principle of least astonishment, and it will probably be better to exclude invalid endpoints by default. Actually, I was in such a confusing situation myself at least two times - I was wondering why the schema is invalid :)

I will change the default config + document this behavior :)

Thank you for bringing this on the table :)

**Comment by Stranger6667** [comment]
Resolved in https://github.com/schemathesis/schemathesis/commit/a96b044d5fd67a39e6c3ed180727b926ed095d42
