### ISSUE TITLE
[BUG] schemathesis fails with validation error despite schema is openapi 3.0.0 valid

### ISSUE THREAD

**Issue by piotr-iohk** [schemathesis/schemathesis#940]
**Describe the bug**
schemathesis fails with validation error despite schema is openapi 3.0.0 valid.

**To Reproduce**

```
$ docker run --network="host" schemathesis/schemathesis:stable run https://gist.githubusercontent.com/piotr-iohk/66270947ddc8fd31540b0377153fa411/raw/5af278fcf02414da17f4f8c622dcf182638034c1/gistfile1.txt --base-url http://localhost:8090 --show-errors-tracebacks

An internal error happened during a test run
Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/schemathesis/runner/__init__.py", line 182, in execute_from_schema
    schema = load_schema(
  File "/usr/local/lib/python3.8/site-packages/schemathesis/runner/__init__.py", line 362, in load_schema
    return loader(
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 83, in from_uri
    return from_file(
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 120, in from_file
    return from_dict(
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 193, in from_dict
    return init_openapi_3()
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 171, in init_openapi_3
    _maybe_validate_schema(raw_schema, definitions.OPENAPI_30, validate_schema)
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 200, in _maybe_validate_schema
    jsonschema.validate(instance, schema)
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'path' is not one of ['query']

Failed validating 'enum' in schema[1]['properties']['in']:
    {'enum': ['query']}

On instance['in']:
    'path'

```

If possible, please post a minimal version of your API schema that cause this behavior:

https://gist.githubusercontent.com/piotr-iohk/66270947ddc8fd31540b0377153fa411/raw/5af278fcf02414da17f4f8c622dcf182638034c1/gistfile1.txt

**Expected behavior**
I suppose it should work.

**Environment (please complete the following information):**
 - OS: [Linux]
 - Python version: [docker]
 - Schemathesis version: [schemathesis, version 2.8.5]
 - Spec version: [Open API 3.0.0]

**Additional context**

Please note that the same schema is valid according to:
```
$ openapi-spec-validator --schema 3.0.0 swagger.json
OK
```

**Comment by piotr-iohk** [comment]
Please note that on yaml version of the same schema the error is:

Input: https://raw.githubusercontent.com/input-output-hk/cardano-wallet/v2020-12-08/specifications/api/swagger.yaml

```
$  docker run --network="host" schemathesis/schemathesis:stable \
>     run https://raw.githubusercontent.com/input-output-hk/cardano-wallet/v2020-12-08/specifications/api/swagger.yaml \
>     --base-url http://localhost:8090 \
>     --show-errors-tracebacks
An internal error happened during a test run
Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 200, in _maybe_validate_schema
    jsonschema.validate(instance, schema)
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 932, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "/usr/local/lib/python3.8/site-packages/jsonschema/exceptions.py", line 370, in best_match
    best = max(itertools.chain([best], errors), key=key)
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.8/site-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.8/site-packages/jsonschema/_validators.py", line 263, in ref
    for error in validator.descend(instance, resolved):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.8/site-packages/jsonschema/_validators.py", line 23, in patternProperties
    for error in validator.descend(
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.8/site-packages/jsonschema/_validators.py", line 263, in ref
    for error in validator.descend(instance, resolved):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.8/site-packages/jsonschema/_validators.py", line 23, in patternProperties
    for error in validator.descend(
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.8/site-packages/jsonschema/_validators.py", line 263, in ref
    for error in validator.descend(instance, resolved):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.8/site-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.8/site-packages/jsonschema/_validators.py", line 263, in ref
    for error in validator.descend(instance, resolved):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.8/site-packages/jsonschema/_validators.py", line 22, in patternProperties
    if re.search(pattern, k):
  File "/usr/local/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/schemathesis/runner/__init__.py", line 182, in execute_from_schema
    schema = load_schema(
  File "/usr/local/lib/python3.8/site-packages/schemathesis/runner/__init__.py", line 362, in load_schema
    return loader(
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 83, in from_uri
    return from_file(
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 120, in from_file
    return from_dict(
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 193, in from_dict
    return init_openapi_3()
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 171, in init_openapi_3
    _maybe_validate_schema(raw_schema, definitions.OPENAPI_30, validate_schema)
  File "/usr/local/lib/python3.8/site-packages/schemathesis/loaders.py", line 202, in _maybe_validate_schema
    raise ValidationError("Invalid schema") from exc
jsonschema.exceptions.ValidationError: Invalid schema

Add this option to your command line parameters to see full tracebacks: --show-errors-tracebacks

You can disable input schema validation with --validate-schema=false command-line option
In this case, Schemathesis cannot guarantee proper behavior during the test run
```

**Comment by Stranger6667** [comment]
Hi! Thank you for reporting. I am looking into it.

Re: YAML version. It is invalid because it has HTTP status codes as integers. See more information in #829. There were multiple discussions in `jsonschema` ([this one](https://github.com/Julian/jsonschema/pull/286), for example). Currently, I have a [WIP PR](843) to improve error messages, but there is a substantial amount of work to be done, but I plan to get back to it in January.

**Comment by Stranger6667** [comment]
Regarding the first part - I am not sure how `openapi-spec-validator` works (will check that out), but Schemathesis uses the `jsonschema` package and official JSON schemas ([this one](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.json) for Open API 3.0). At the moment we simply propagate errors from `jsonschema` which are too generic and don't give much useful info in many cases (I want to address it in the PR I mentioned above), especially when the used schema includes `oneOf` / `anyOf` keywords.

In this case, some "path" parameters are missing `required: true`, which is required by the spec (see the "required" row in [this table](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#fixed-fields-10)). My assumption is that with `--validate-schema=false`, Schemathesis will output a more detailed error - there is special handling exactly for this case.

The affected parameters are "role" and `"index" in `/wallets/{walletId}/keys/{role}/{index}` and in `/wallets/{walletId}/signatures/{role}/{index}`

**Comment by Stranger6667** [comment]
Let me know if I can provide more info regarding this behavior.

In the future, I think Schemathesis can enforce `required: true` for such cases, when `--validate-schema=false` is passed, so that it is still explicit that the schema doesn't validate, but otherwise will run without raising an error in runtime (or maybe a warning).

**Comment by piotr-iohk** [comment]
Thanks for the quick answer! 
Actually when trying with `--validate-schema=false` it seems to be hanging infinitely. There is no output produced or anything even with the debug verbosity.

```
$ docker run --network="host" schemathesis/schemathesis:stable \
>     run https://gist.githubusercontent.com/piotr-iohk/66270947ddc8fd31540b0377153fa411/raw/5af278fcf02414da17f4f8c622dcf182638034c1/gistfile1.txt \
>     --base-url http://localhost:8090 \
>     --validate-schema=false \
>     --hypothesis-verbosity debug
```

**Comment by Stranger6667** [comment]
I assume that it stuck on the data-generation phase in `hypothesis-jsonschema`. The underlying problem is that it tries to canonicalise the input schema, which involves many computations (mostly to simplify generation later on). I am working on this problem in [this PR](https://github.com/Zac-HD/hypothesis-jsonschema/pull/69), which is close to its finished state - I hope to finalize it in the next few weeks. 

Still, the performance part might not be enough in some cases - the schema you linked is >1 MB, which is quite a lot for the current Python-based implementation (it does a lot of jsonschema validation calls & son serialization). I have a couple of components written in Rust (e.g. [this one](https://github.com/Stranger6667/jsonschema-rs)) that solve some aspects, but it will take time to integrate them. Most likely, they will be available in schemathesis.io first and later in the opensource version.

For the current state of things, I don't see an immediate way to make it work :(

However, I am currently involved in research where we plan to run different web API fuzzing tools against open source services. I will try to add https://github.com/input-output-hk/cardano-wallet there and run our experiments. There is quite a lot of computational resources & time, so it will help to untackle this issue in more detail and, hopefully, verify if the fixes we plan to add will solve this schema's performance problem.

**Comment by piotr-iohk** [comment]
> I will try to add https://github.com/input-output-hk/cardano-wallet there and run our experiments.

Thanks! Much appreciated!

**Comment by piotr-iohk** [comment]
Just to confirm. With the fixed schema (thanks for pointing that out!) it gets "stuck" also.

Fixed schema: https://gist.githubusercontent.com/piotr-iohk/2edd8c247d02fc1fe2d28a5b4471dd06/raw/2f36055af2dfbd47e5685711ea2828dfcb147033/swaggerv2020-12-21.json

```
$ docker run --network="host" schemathesis/schemathesis:stable \
>    run https://gist.githubusercontent.com/piotr-iohk/2edd8c247d02fc1fe2d28a5b4471dd06/raw/2f36055af2dfbd47e5685711ea2828dfcb147033/swaggerv2020-12-21.json \
>    --base-url http://localhost:8090/v2
```

**Comment by Stranger6667** [comment]
Thank you for letting me know!

As far as I see, the initial issue with validation is resolved somehow (at least the reason for this behavior is clearer), and I close this issue. 

Related issues:
- Enforcing `required: true` - #941. Implemented and available in the `latest` docker image. Now, passing `--validate-schema=false` will fix those path parameter cases in runtime, and test data will be generated (unless that performance issue is in place)
- Improved validation errors - #834 
- Performance - #945. Here I'll continue with the performance problems you experienced in a more narrow scope.

Thank you again for bringing this to the table! I appreciate it :)

**Comment by Stranger6667** [comment]
@piotr-iohk 
FYI, I was wrong regarding the cause of Schemathesis being stuck on this schema, it was inside Schemathesis, not `hypothesis-jsonschema`. Now, the `latest` Docker tag includes the fix for it and Schemathesis generates test cases (they are failing due to me not having an actual server running locally):

```bash
⇒  docker run --network="host" schemathesis/schemathesis:latest run https://gist.githubusercontent.com/piotr-iohk/2edd8c247d02fc1fe2d28a5b4471dd06/raw/2f36055af2dfbd47e5685711ea2828dfcb147033/swaggerv2020-12-21.json --base-url=http://0.0.0.0
======================= Schemathesis test session starts =======================
platform Linux -- Python 3.8.7, schemathesis-2.8.5, hypothesis-5.43.4, hypothesis_jsonschema-0.18.2, jsonschema-3.2.0
rootdir: /app
hypothesis profile 'default' -> database=InMemoryExampleDatabase({})
Schema location: https://gist.githubusercontent.com/piotr-iohk/2edd8c247d02fc1fe2d28a5b4471dd06/raw/2f36055af2dfbd47e5685711ea2828dfcb147033/swaggerv2020-12-21.json
Base URL: http://0.0.0.0
Specification version: Open API 3.0.0
Workers: 1
collected endpoints: 52

POST /wallets/{walletId}/signatures/{role}/{index} F                     [  1%]
```

The test generation is quite slow, though, but it seems acceptable to me (let me know if it is too slow for your use case). Also, Schemathesis will show an error message on operations that are currently not supported due to recursive reference support in `hypothesis-jsonschema`. The good news is I can confirm that [this PR](https://github.com/Zac-HD/hypothesis-jsonschema/pull/69) fixes it, and eventually, we'll have complete support for recursive references :) 

I also suggest adding `--hypothesis-suppress-health-checks=too_slow,filter_too_much` to the command-line options to avoid having some tests failed due to internal health checks. So, test cases will be generated, but it may be slow (but should not be stuck!). Then those Rust extensions & relevant measures I mentioned will likely improve performance for such schemas.
